[package]
name = "meshoptimizer-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meshopt = { git = "https://github.com/vtroxi/meshopt-rs" }
tobj = "4.0.0"
